sudo: required
services:
- docker
env:
  global:
  - VERSIONS="0.10,4"
  - secure: fQUtoSb/Bkp3khxlC+S63AJ9c0bGJkr3Y7Bg8l5F4tPLuQu67sHQZtZc1JKM2vc45F9QrSbo3UxBmm9ypT+CnZfaOEAN1KMHGYWwl47aiAQmF/nvrCpo3ZgVgkDa3Ju7kR4i8cNLytK5YKlhJ0yylUyoO5WszvaeuitlmkP+QtV6vcctkFQYYARzj2idEszhYbJhX54EL+OTst5G9fBz7GLKaXXBJ5vECYY5wUU+pevUy8/tR+iHNf28pwSB6B1hJOP8yYwpt8+D0dqMEWnpQdySLUACJMfJaqFwkfK+mCxlo+3zNGAb62/i/HtzMdxW9NjMtkPDtX6vgUieKFEm2uryXbyPeCe0VbfeaOcrGj3IuyHkAWyf7CUuH3iZksigj9zYVTWsqckXIAJeyJiXqPWgKr8nC+as7J82L+A8mG9kJW2tQnsxKPjQId2HB4F7o2Dzh78RAAkG5HRI29eu2Mbe1zmhGW9H41AdvyvV9PyUSYGDlhLZ0YEsmIySUcKTcVR1sAw92AkppF1/8vxSPeXFdSI5oeN0UbPEPiCnYru+UD+qs/COrqBc/QsJ8XGDU0AKcLYTblBsd27NCNhMtZ7jnuz6mascbt3pW3quL73oqbfwVXvThLuoq8Qb8jp5ZpAy6lZzzDkRwn6FtgGDF45xAPCxSbsLQfd+6O5iLaw=
script:
- ". test/run"
notifications:
  slack:
    secure: t72I4V8RhblFjXudwnDe66XHPotyBCTY5cU6dNmViMpOgNyGuy5C/1Nfiv8/A4okrVLLtkgxc3rU6mZbrWD8cnlHQ1a5EuXznGtLkcjYmRw1eBTMmzvNIsSDv7c8StLxfMkTgL4Tm1c8f8HLjaiueIy6t7KzsSWcgOSH3AmPxPeII/g1hLuW/kvl14G8NUolqL3Y8l2L1ZUaxl3x/BBOCI2sWUxGhEWZSxgi3pQN/oPTqiJxl6i/G4jxNFFcKaRRNM9d6oLT68Up1dgsmZ6urhoECISMMAfKZa4kPQJXLNl+zHjwtPDc3cpVDNJg5OhQSrI4z1RgHiamNksEicheDnR//k2R9hJNntuzjOzCgNXG5enZ3rbY6OZkyqJZDcSq+8gRUTY+X96/Bde23MhKu6ziRY3vqgjrMg66CqQ5De4ZqMdsJDkFOVnH831TNBiNFBNOfrf1Ejk13qm3RmREzhXpCvtNga8XnwgQ2TyGcQH2C9kr4hoeMOyt32fME/XbTeEV+4l/cRu4394ABjEdSI7eiv/cq+ObT+FyhZho7t7bKr/yRxcKF2exp15e0wDELqUqlNCfzg0a+REw7BaEdrXtjVZpc8gldCL9r/LLuPFrpwdrqC/L5K4yLnaxwrUxqwtugTCcCtLrgghxrBoXajdG1TYg89EJd0TKFNzWpog=
